import { bootstrapApplication } from '@angular/platform-browser';

import { AppComponent } from './app/app.component';
import { TasksService } from './app/tasks/tasks.service';
import { InjectionToken } from '@angular/core';

export const TaskServiceToken = new InjectionToken<TasksService>('tasks-service-token');

bootstrapApplication(AppComponent, {
    // This will always be included in the initial code bundle generated by angular
    // Alternate approach of @Injectable decorator for service

    // Registered TaskService with application root injector 
    // providers: [TasksService]  

    
    providers: [{ provide: TaskServiceToken, useClass: TasksService }]  
}).catch((err) => console.error(err));

// default 
// bootstrapApplication(AppComponent).catch((err) => console.error(err));