import { bootstrapApplication } from '@angular/platform-browser';

import { AppComponent } from './app/app.component';
// import { TasksService } from './app/tasks/tasks.service';

// bootstrapApplication(AppComponent, {
    // This will always be included in the initial code bundle generated by angular
    // Alternate approach of @Injectable decorator for service
    // providers: [TasksService]  // Registered TaskService with application root injector 
// }).catch((err) => console.error(err));

// default 
bootstrapApplication(AppComponent).catch((err) => console.error(err));